
// Benefits Tool
export const TOOL_COOKIES_LOADED = 'TOOL_COOKIES_LOADED';
export const TOOL_COOKIES_LOAD_FAILED = 'TOOL_COOKIES_LOAD_FAILED';
export const ANSWERS_CLEAR = 'ANSWERS_CLEAR';
export const QUESTION_INIT = 'QUESTION_INIT';
export const ANSWERS_UPDATE_STARTED = 'ANSWERS_UPDATE_STARTED';
export const ANSWERS_UPDATE_COMPLETED = 'ANSWERS_UPDATE_COMPLETED';
export const ANSWERS_UPDATE_FAILED = 'ANSWERS_UPDATE_FAILED';
export const ANSWERS_PUSH_STARTED = 'ANSWERS_PUSH_STARTED';
export const ANSWERS_PUSH_COMPLETED = 'ANSWERS_PUSH_COMPLETED';
export const ANSWERS_PUSH_FAILED = 'ANSWERS_PUSH_FAILED';
export const VISITOR_PREFS_STORED = 'VISITOR_PREFS_STORED';

// Prelaunch Login
export const PRELAUNCH_LOGIN_CHECK_STARTED = 'PRELAUNCH_LOGIN_CHECK_STARTED';
export const PRELAUNCH_LOGIN_STARTED = 'PRELAUNCH_LOGIN_STARTED';
export const PRELAUNCH_LOGIN_FAILED = 'PRELAUNCH_LOGIN_FAILED';
export const PRELAUNCH_LOGIN_SUCCEEDED = 'PRELAUNCH_LOGIN_SUCCEEDED';
export const PRELAUNCH_LOGOUT = 'PRELAUNCH_LOGOUT';

// Admin: Auth
export const ADMIN_LOGIN_CHECK_STARTED = 'ADMIN_LOGIN_CHECK_STARTED';
export const ADMIN_LOGIN_STARTED = 'ADMIN_LOGIN_STARTED';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGIN_SUCCEEDED = 'ADMIN_LOGIN_SUCCEEDED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

// Admin: Dashboard
export const ADMIN_DASH_RESPONSES_STARTED = 'ADMIN_DASH_RESPONSES_STARTED';
export const ADMIN_DASH_RESPONSES_FAILED = 'ADMIN_DASH_RESPONSES_FAILED';
export const ADMIN_DASH_RESPONSES_SUCCEEDED = 'ADMIN_DASH_RESPONSES_SUCCEEDED';
export const ADMIN_DASH_CONTACTS_STARTED = 'ADMIN_DASH_CONTACTS_STARTED';
export const ADMIN_DASH_CONTACTS_FAILED = 'ADMIN_DASH_CONTACTS_FAILED';
export const ADMIN_DASH_CONTACTS_SUCCEEDED = 'ADMIN_DASH_CONTACTS_SUCCEEDED';

// Admin: Responses
export const ADMIN_RESPONSES_STARTED = 'ADMIN_RESPONSES_STARTED';
export const ADMIN_RESPONSES_FAILED = 'ADMIN_RESPONSES_FAILED';
export const ADMIN_RESPONSES_SUCCEEDED = 'ADMIN_RESPONSES_SUCCEEDED';

