export const BENEFITS_TOOL_LOADED = 'BENEFITS_TOOL_LOADED';
export const BENEFITS_TOOL_UPDATE_ANSWERS = 'BENEFITS_TOOL_UPDATE_ANSWERS';
export const BENEFITS_TOOL_ERROR_ON_LOADING = 'BENEFITS_TOOL_ERROR_ON_LOADING';
